sudo: required
language: node_js

node_js:
  - "8"

services:
  - docker

before_install:
  - sudo apt-get install -y libjpeg-dev graphicsmagick graphicsmagick-imagemagick-compat libpango1.0-dev libcairo2-dev libgif-dev

script:
  - npm test
  - ./bin/openpaas init --dir=openpaas-travis
